version: "3"

services:
  database:
    image: mariadb:latest
    container_name: Database
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: jshortener
      MYSQL_PASSWORD: 0123456789
      MYSQL_ROOT_PASSWORD: 9876543210
    volumes:
      - "./database:/var/lib/mysql:rw"

  jshortener:
    image: pryoscode/jshortener:latest
    container_name: JShortener
    restart: always
    ports:
      - 80:80
    environment:
      JS_SHORT_LENGTH: 5
      JS_WEB_PORT: 80
      JS_WEB_STATUS: 302
      JS_WEB_ROOT: "https://github.com/PryosCode/JShortener"
      JS_WEB_404: ""
      JS_DB_TYPE: "mysql"
      JS_DB_HOST: "database"
      JS_DB_PORT: 3306
      JS_DB_USER: "jshortener"
      JS_DB_PASSWORD: "0123456789"
      JS_VM_THREADS: 3
