name: Build

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Gradle
      run: |
        chmod +x gradlew
        ./gradlew shadowJar
        ./gradlew -q properties | grep "version:" | cut -d ' ' -f 2 >> $GRADLE_VERSION

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/JShortener.jar
        tag_name: ${{ env.GRADLE_VERSION }}
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}