name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Gradle
      run: |
        gradle shadowJar
        echo GRADLE_VERSION=$(gradle -q properties | grep 'version:' | cut -d ' ' -f 2) >> $GITHUB_ENV

    - name: Login Docker Hub
      uses: docker/login-action@v1
      with:
        username: pryoscode
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Hub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          pryoscode/jshortener:latest
          pryoscode/jshortener:${{ env.GRADLE_VERSION }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/libs/JShortener.jar
        tag_name: v${{ env.GRADLE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}